apiVersion: v1
kind: Service
metadata:
  name: postgresql-operator
  namespace: pgo
spec:
  ports:
  - name: nodeport
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 32443
  selector:
    name: postgres-operator
    vendor: crunchydata
  sessionAffinity: None
  type: NodePort
